/***
  BEGIN LICENSE

  Copyright(C) 2013-2014 Fabien Cortina <fabien.cortina@gmail.com>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.

  END LICENSE
***/

/* This file is generated by CMake. Do NOT edit it */

namespace Build {
    public const string DATADIR = "@DATADIR@";
    public const string PKGDATADIR = "@PKGDATADIR@";
    public const string PLUGIN_DIR = "@PLUGIN_DIR@";
    public const string GETTEXT_PACKAGE = "@GETTEXT_PACKAGE@";
    public const string RELEASE_NAME = "@RELEASE_NAME@";
    public const string VERSION = "@VERSION@";
    public const string VERSION_INFO = "@VERSION_INFO@";
}